version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - "5601:5601"
  nodejs-server:
    build:
      context: ./react-nodejs-docker-compose/api
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
       - ./react-nodejs-docker-compose/api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  react-ui:
    build:
      context: ./react-nodejs-docker-compose/my-app
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./react-nodejs-docker-compose/my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules