version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=MbxpC6ssdThoSxy20PdL
      - xpack.security.audit.enabled=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      -  ..\..\..\es\:/usr/share/elasticsearch/data
#      -  ..\..\..\keys\:/usr/share/elasticsearch/config
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.0.0
    volumes:
      - .\Kibana\kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"

  logstash:
    labels:
      com.example.service: "logstash"
      com.example.description: "For logging data"
    image: logstash:8.0.0
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - .\Logstash\logstash.conf:/etc/logstash/conf.d/logstash.conf
      - .\Logstash\logstash.yml:/usr/share/logstash/config/logstash.yml
      - ..\data\:/usr/share/logstash/data/
#      - C:\Users\Oz Ohayon\user data
    depends_on:
      - kibana
    ports:
      - "5959:5959"
#  BCL2fastq:
#    build:
#      context: .\
#      dockerfile: .\Dockerfile
#    image: bcl2fastq2-v2.20.0.422
#    volumes:
#      - ..\data\qc_data:/scratch
#
#  fastqc:
#    image: conradstoerker/fastqc
#    volumes:
#      - ..\data\qc_data:/fastqc/data/
#  multiqc:
#    image: ewels/multiqc
#    volumes:
#      - ..\data\qc_data:/multiqc/data/
#  cutadapt:
#    build:
#      context: .\
#      dockerfile: .\Cutadapt\Dockerfile
#    image: dceoy/cutadapt
#    volumes:
#      - ..\data\qc_data:/cutadapt/data/
#  hmp-qc-dada2:
#    build:
#      context: .
#      args:
#        PLATFORM: illumina
#    image: umigs/hmp-qc-dada2:latest
#    volumes:
#      - ..\data\qc_data:/dada2/data/input
#      - ..\data\qc_data:/dada2/data/output:ro
#    environment:
##      - SRS_ID=SRR6704301
##      - INPUT_PREFIX=SRR6704301
#      - PLATFORM=illumina

#  BCL2fastq:
#    depends_on:
#      - elasticsearch
#    image: docker.elastic.co/kibana/kibana:8.0.0
#    volumes:
#      - .\Kibana\kibana.yml:/usr/share/kibana/config/kibana.yml
#    ports:
#      - "5601:5601"

#  filebeat:
#    image: "docker.elastic.co/beats/filebeat:8.0.0"
#    user: root
#    volumes:
#      - .\Filebeat\filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#      - /var/lib/docker:/var/lib/docker:ro
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - logstash

#  react-ui:
#    build:
#      context: ./react-nodejs-docker-compose/my-app
#    ports:
#      - "3000:3000"
#    container_name: react-ui
#    stdin_open: true
#    volumes:
#       - ./react-nodejs-docker-compose/my-app:/usr/src/app/my-app
#       - /usr/src/app/my-app/node_modules
#  nodejs-server:
#    build:
#      context: ./react-nodejs-docker-compose/api
#    ports:
#      - "3080:3080"
#    container_name: node-api
#    volumes:
#       - ./react-nodejs-docker-compose/api:/usr/src/app/api
#       - /usr/src/app/api/node_modules